# Generated by Django 5.2.10 on 2026-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('coordinates', models.JSONField(default=dict)),
            ],
        ),
    ]
