# Generated by Django 5.2.10 on 2026-02-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='coordinates',
        ),
    ]
