# Generated by Django 5.2.10 on 2026-04-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_remove_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Место, к которому привязана картинка'),
            preserve_default=False,
        ),
    ]
