# Generated by Django 5.2.10 on 2026-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Номер'),
        ),
    ]
